[package]
name = "treebag-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
eyre = "0.6.5"
log = "0.4.14"
rustyline = "9.1.1"
thiserror = "1.0.30"
